

###
POST http://localhost:3000/send/text
Content-Type: application/json  

{
  "to": "5515996920983",
  "body": "hello"
}



###
POST https://test-1-oq5o.onrender.com/send/text
Content-Type: application/json  

{
  "to": "5515996920983",
  "body": "hello"
}


###
POST https://test-1-oq5o.onrender.com/webhook
Content-Type: application/json

{
  "object": "whatsapp_business_account",
  "entry": [
    {
      "id": "123456",
      "changes": [
        {
          "field": "messages",
          "value": {
            "messaging_product": "whatsapp",
            "metadata": {
              "display_phone_number": "5511999998888",
              "phone_number_id": "123456789"
            },
            "contacts": [
              {
                "profile": {
                  "name": "Tito Test"
                },
                "wa_id": "5511999998888"
              }
            ],
            "messages": [
              {
                "from": "5511999998888",
                "id": "ABGGFlA5",
                "timestamp": "1710000000",
                "text": {
                  "body": "oi"
                },
                "type": "text"
              }
            ]
          }
        }
      ]
    }
  ]
}



###
POST https://test-1-oq5o.onrender.com/webhook
Content-Type: application/json  



{
  "sample": {
    "field": "account_settings_update",
    "value": {
      "messaging_product": "whatsapp",
      "timestamp": "1671644824",
      "type": "phone_number_settings",
      "phone_number_settings": {
        "phone_number_id": "123456123",
        "calling": {
          "status": "ENABLED",
          "call_icon_visibility": "DEFAULT",
          "callback_permission_status": "ENABLED",
          "call_hours": {
            "status": "DISABLED"
          },
          "sip": {
            "status": "DISABLED"
          }
        }
      }
    }
  },
  "sub_field_options": null,
  "sample_context_metadata": null
}